### ISSUE TITLE
r1glms assertion error

### ISSUE THREAD

**Issue by rfarouni** [fabianp/hrf_estimation#4]
Hi,

 When I tried to use the 'r1glms' option in the iPython notebook example, I got the following error:

```python
drifts = np.ones((voxels.shape[0], 1))
hrfs, betas = he.glm(conditions, onsets, 1., voxels, drifts=drifts, mode='r1glms', basis='3hrf', verbose=1)
.. creating design matrix ..
.. done creating design matrix ..
.. computing initialization ..
.. done initialization ..
Traceback (most recent call last):

  File "<ipython-input-6-16194dc738f8>", line 3, in <module>
    hrfs, betas = he.glm(conditions, onsets, 1., voxels, drifts=drifts, mode='r1glms', basis='3hrf', verbose=1)

  File "/home/rick/anaconda/lib/python2.7/site-packages/hrf_estimation/rank_one_.py", line 429, in glm
    for y_i, w_i in zip(Y_split, W_init_split))

  File "/home/rick/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)

  File "/home/rick/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)

  File "/home/rick/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)

  File "/home/rick/anaconda/lib/python2.7/site-packages/hrf_estimation/rank_one_.py", line 216, in rank_one
    assert w_i.shape[0] == n_basis + 2 * size_v + drifts.shape[1]

AssertionError
```

I also tried the same thing on a different dataset but also got the same error.

**Comment by fabianp** [comment]
Hi @rfarouni.

Thanks for the report!. I fixed it in master and made a new release, so running `pip install -U hrf_estimation` should fix the problem. The situation right now is that when specifying the model r1glms the vector of drifts gets ignored. I could implement this if there is demand for it, but in my experience the r1glm model provides very similar results with a fraction of running time.

**Comment by rfarouni** [comment]
Hi Fabian,

Thanks for the quick fix :). It tried it now on an OpenFmri dataset (i.e. ds117) with TR=2 but the hrf estimates I get are all in the order of e07 -except for the first row, which is all ones. The beta estimates are mostly zero. I am not sure why this happened. Is it possible that the algorithm didn't converge? For the test run, I choose 500 voxels randomly. Also when  I try 'r1glm' on the same dataset, I get the following error. 
```python
hrfs, betas = he.glm(conditions, onsets, 2.0, voxels, mode='r1glm', basis='fir',hrf_length=20,verbose=2)

File "/home/rick/anaconda/lib/python2.7/site-packages/hrf_estimation/rank_one_.py", line 464, in glm
    sign = np.sign(np.dot(U.T, hrf.spmt(xx)))
ValueError: shapes (500,10) and (20,) not aligned: 10 (dim 1) != 20 (dim 0)
```
Rick,

**Comment by rfarouni** [comment]
Oh another minor thing I found is when I ask for the design matrix back in the case of glms, I get the following error

```python
hrfs, betas, design = he.glm(conditions, onsets, 2.0, voxels, mode='glms',
                     basis='fir',hrf_length=20,verbose=2,return_design_matrix=True)  
.. creating design matrix ..
.. done creating design matrix ..
Traceback (most recent call last):

  File "<ipython-input-22-3e4feab41312>", line 2, in <module>
    basis='fir',hrf_length=20,verbose=2,return_design_matrix=True)

  File "/home/rick/anaconda/lib/python2.7/site-packages/hrf_estimation/rank_one_.py", line 470, in glm
    out.append(X_design.toarray())

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

```
It seems to get fixed if I remove  .toarray()  in line 470 since the matrix returned is not sparse if I am not mistaken

**Comment by fabianp** [comment]
Hi,

I think I fixed the last thing. As for the other questions, you will need to normalize in order to get the estimate (the r1glm with 3hrf basis does it but not the others), i.e. divide for example each of the estimated hrfs by its maximum and multiply the betas by the same quantity. As you have noticed, the first measurement of the HRF is equal to 1. This is set so that the optimization algorithm converges better but you definitely need to re-normalize to get something meaningful. Since you say that the hrfs are of the order of 1e7 and the betas mostly zero this should level things up. 

As for the shape mismatch error that you report, that looks like a bug, I'm going to look into it.

**Comment by RebekkaHeinen** [comment]
Hi Fabian,

I am running into the same problem as Rick Farouni  when using a rank-1-glm model with a TR of 2.0 seconds and fir as basis function.
I get the following error from rank_one_.py: 

![image](https://user-images.githubusercontent.com/13535452/37819178-dc4ab1f6-2e7c-11e8-8ae0-1fefc1ae3152.png)
I was able to find a function in the hrf.py that sets the TR to 1.0 and changed it to 2.0 but I still end up with the value error and I am also not sure whether the fir function was set to have a TR of 1.0 for a reason and should stay untouched.

![screenshot from 2018-03-23 09-42-02](https://user-images.githubusercontent.com/13535452/37819684-9b9e5fc0-2e7e-11e8-9ec4-56c6107ffb79.png)


Is there any solution to this issue?
